main:
  steps:
    - startBuild:
        call: googleapis.cloudbuild.v1.projects.locations.triggers.run
        args:
          name: ${"projects/" + sys.get_env("CLOUD_BUILD_TRIGGER_PROJECT_ID") + "/locations/global/triggers/" + sys.get_env("CLOUD_BUILD_TRIGGER_ID")}
          body:
            source:
              branchName: ${sys.get_env("CLOUD_BUILD_TRIGGER_BRANCH_NAME")}
# - init:
#     assign:
#       - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
#       - location_id: "global"
#       - repo: ${project_id + "-docker-repo"}
#       - image_path: ${"us-central1-docker.pkg.dev/" + project_id + "/" + repo + "/quickstart-image:tag1"}
