steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'REGISTRY_URL=$_ARTIFACT_REGISTRY_BASE_URL'
      - 'IMAGE_NAME=$_IMAGE_NAME'
    entrypoint: 'bash'
    args:
      - './build_image.sh'
    dir: image

options:
  logging: CLOUD_LOGGING_ONLY
